champion = { #챔피언 인덱스번호 딕셔너리 / 이대로 사용하면 불편해서 아래에 이 dictionary의 key, value 값을 바꿔줄 거임
'Aatrox': [],
'Ahri': [],
'Akali': [],
'Akshan': [],
'Alistar': [],
'Amumu': [],
'Anivia': [],
'Annie': [],
'Aphelios': [],
'Ashe': [],
'Aurelion Sol': [],
'Azir': [],
'Bard': [],
"Bel'Veth": [],
'Blitzcrank': [],
'Brand': [],
'Braum': [],
'Caitlyn': [],
'Camille': [],
'Cassiopeia': [],
"Cho'Gath": [],
'Corki': [],
'Darius': [],
'Diana': [],
'Draven': [],
'Dr. Mundo': [],
'Ekko': [],
'Elise': [],
'Evelynn': [],
'Ezreal': [],
'Fiddlesticks': [],
'Fiora': [],
'Fizz': [],
'Galio': [],
'Gangplank': [],
'Garen': [],
'Gnar': [],
'Gragas': [],
'Graves': [],
'Gwen': [],
'Hecarim': [],
'Heimerdinger': [],
'Illaoi': [],
'Irelia': [],
'Ivern': [],
'Janna': [],
'Jarvan IV': [],
'Jax': [],
'Jayce': [],
'Jhin': [],
'Jinx': [],
"Kai'Sa": [],
'Kalista': [],
'Karma': [],
'Karthus': [],
'Kassadin': [],
'Katarina': [],
'Kayle': [],
'Kayn': [],
'Kennen': [],
"Kha'Zix": [],
'Kindred': [],
'Kled': [],
"Kog'Maw": [],
"K'Sante": [],
'LeBlanc': [],
'Lee Sin': [],
'Leona': [],
'Lillia': [],
'Lissandra': [],
'Lucian': [],
'Lulu': [],
'Lux': [],
'Malphite': [],
'Malzahar': [],
'Maokai': [],
'Master Yi': [],
'Milio': [],
'Miss Fortune': [],
'Wukong': [],
'Mordekaiser': [],
'Morgana': [],
'Naafiri': [],
'Nami': [],
'Nasus': [],
'Nautilus': [],
'Neeko': [],
'Nidalee': [],
'Nilah': [],
'Nocturne': [],
'Nunu & Willump': [],
'Olaf': [],
'Orianna': [],
'Ornn': [],
'Pantheon': [],
'Poppy': [],
'Pyke': [],
'Qiyana': [],
'Quinn': [],
'Rakan': [],
'Rammus': [],
"Rek'Sai": [],
'Rell': [],
'Renata Glasc': [],
'Renekton': [],
'Rengar': [],
'Riven': [],
'Rumble': [],
'Ryze': [],
'Samira': [],
'Sejuani': [],
'Senna': [],
'Seraphine': [],
'Sett': [],
'Shaco': [],
'Shen': [],
'Shyvana': [],
'Singed': [],
'Sion': [],
'Sivir': [],
'Skarner': [],
'Sona': [],
'Soraka': [],
'Swain': [],
'Sylas': [],
'Syndra': [],
'Tahm Kench': [],
'Taliyah': [],
'Talon': [],
'Taric': [],
'Teemo': [],
'Thresh': [],
'Tristana': [],
'Trundle': [],
'Tryndamere': [],
'Twisted Fate': [],
'Twitch': [],
'Udyr': [],
'Urgot': [],
'Varus': [],
'Vayne': [],
'Veigar': [],
"Vel'Koz": [],
'Vex': [],
'Vi': [],
'Viego': [],
'Viktor': [],
'Vladimir': [],
'Volibear': [],
'Warwick': [],
'Xayah': [],
'Xerath': [],
'Xin Zhao': [],
'Yasuo': [],
'Yone': [],
'Yorick': [],
'Yuumi': [],
'Zac': [],
'Zed': [],
'Zeri': [],
'Ziggs': [],
'Zilean': [],
'Zoe': [],
'Zyra': []
}

champion_dic = { #챔피언별 위치데이터(매 판 분 수 다를거임, 즉 컬럼 수 다를거임 / 패딩해서 넣어줘야 함 넣을 때)
'Aatrox (Aatrox)': [],
'Ahri (Ahri)': [],
'Akali (Akali)': [],
'Akshan (Akshan)': [],
'Alistar (Alistar)': [],
'Amumu (Amumu)': [],
'Anivia (Anivia)': [],
'Annie (Annie)': [],
'Aphelios (Aphelios)': [],
'Ashe (Ashe)': [],
'Aurelion Sol (AurelionSol)': [],
'Azir (Azir)': [],
'Bard (Bard)': [],
'Bel\'Veth (Belveth)': [],
'Blitzcrank (Blitzcrank)': [],
'Brand (Brand)': [],
'Braum (Braum)': [],
'Caitlyn (Caitlyn)': [],
'Camille (Camille)': [],
'Cassiopeia (Cassiopeia)': [],
'Cho\'Gath (Chogath)': [],
'Corki (Corki)': [],
'Darius (Darius)': [],
'Diana (Diana)': [],
'Draven (Draven)': [],
'Dr. Mundo (DrMundo)': [],
'Ekko (Ekko)': [],
'Elise (Elise)': [],
'Evelynn (Evelynn)': [],
'Ezreal (Ezreal)': [],
'Fiddlesticks (Fiddlesticks)': [],
'Fiora (Fiora)': [],
'Fizz (Fizz)': [],
'Galio (Galio)': [],
'Gangplank (Gangplank)': [],
'Garen (Garen)': [],
'Gnar (Gnar)': [],
'Gragas (Gragas)': [],
'Graves (Graves)': [],
'Gwen (Gwen)': [],
'Hecarim (Hecarim)': [],
'Heimerdinger (Heimerdinger)': [],
'Illaoi (Illaoi)': [],
'Irelia (Irelia)': [],
'Ivern (Ivern)': [],
'Janna (Janna)': [],
'Jarvan IV (JarvanIV)': [],
'Jax (Jax)': [],
'Jayce (Jayce)': [],
'Jhin (Jhin)': [],
'Jinx (Jinx)': [],
'Kai\'Sa (Kaisa)': [],
'Kalista (Kalista)': [],
'Karma (Karma)': [],
'Karthus (Karthus)': [],
'Kassadin (Kassadin)': [],
'Katarina (Katarina)': [],
'Kayle (Kayle)': [],
'Kayn (Kayn)': [],
'Kennen (Kennen)': [],
'Kha\'Zix (Khazix)': [],
'Kindred (Kindred)': [],
'Kled (Kled)': [],
'Kog\'Maw (KogMaw)': [],
'K\'Sante (KSante)': [],
'LeBlanc (Leblanc)': [],
'Lee Sin (LeeSin)': [],
'Leona (Leona)': [],
'Lillia (Lillia)': [],
'Lissandra (Lissandra)': [],
'Lucian (Lucian)': [],
'Lulu (Lulu)': [],
'Lux (Lux)': [],
'Malphite (Malphite)': [],
'Malzahar (Malzahar)': [],
'Maokai (Maokai)': [],
'Master Yi (MasterYi)': [],
'Milio (Milio)': [],
'Miss Fortune (MissFortune)': [],
'Wukong (MonkeyKing)': [],
'Mordekaiser (Mordekaiser)': [],
'Morgana (Morgana)': [],
'Naafiri (Naafiri)': [],
'Nami (Nami)': [],
'Nasus (Nasus)': [],
'Nautilus (Nautilus)': [],
'Neeko (Neeko)': [],
'Nidalee (Nidalee)': [],
'Nilah (Nilah)': [],
'Nocturne (Nocturne)': [],
'Nunu & Willump (Nunu)': [],
'Olaf (Olaf)': [],
'Orianna (Orianna)': [],
'Ornn (Ornn)': [],
'Pantheon (Pantheon)': [],
'Poppy (Poppy)': [],
'Pyke (Pyke)': [],
'Qiyana (Qiyana)': [],
'Quinn (Quinn)': [],
'Rakan (Rakan)': [],
'Rammus (Rammus)': [],
'Rek\'Sai (RekSai)': [],
'Rell (Rell)': [],
'Renata Glasc (Renata)': [],
'Renekton (Renekton)': [],
'Rengar (Rengar)': [],
'Riven (Riven)': [],
'Rumble (Rumble)': [],
'Ryze (Ryze)': [],
'Samira (Samira)': [],
'Sejuani (Sejuani)': [],
'Senna (Senna)': [],
'Seraphine (Seraphine)': [],
'Sett (Sett)': [],
'Shaco (Shaco)': [],
'Shen (Shen)': [],
'Shyvana (Shyvana)': [],
'Singed (Singed)': [],
'Sion (Sion)': [],
'Sivir (Sivir)': [],
'Skarner (Skarner)': [],
'Sona (Sona)': [],
'Soraka (Soraka)': [],
'Swain (Swain)': [],
'Sylas (Sylas)': [],
'Syndra (Syndra)': [],
'Tahm Kench (TahmKench)': [],
'Taliyah (Taliyah)': [],
'Talon (Talon)': [],
'Taric (Taric)': [],
'Teemo (Teemo)': [],
'Thresh (Thresh)': [],
'Tristana (Tristana)': [],
'Trundle (Trundle)': [],
'Tryndamere (Tryndamere)': [],
'Twisted Fate (TwistedFate)': [],
'Twitch (Twitch)': [],
'Udyr (Udyr)': [],
'Urgot (Urgot)': [],
'Varus (Varus)': [],
'Vayne (Vayne)': [],
'Veigar (Veigar)': [],
'Vel\'Koz (Velkoz)': [],
'Vex (Vex)': [],
'Vi (Vi)': [],
'Viego (Viego)': [],
'Viktor (Viktor)': [],
'Vladimir (Vladimir)': [],
'Volibear (Volibear)': [],
'Warwick (Warwick)': [],
'Xayah (Xayah)': [],
'Xerath (Xerath)': [],
'Xin Zhao (XinZhao)': [],
'Yasuo (Yasuo)': [],
'Yone (Yone)': [],
'Yorick (Yorick)': [],
'Yuumi (Yuumi)': [],
'Zac (Zac)': [],
'Zed (Zed)': [],
'Zeri (Zeri)': [],
'Ziggs (Ziggs)': [],
'Zilean (Zilean)': [],
'Zoe (Zoe)': [],
'Zyra (Zyra)': []
}